### PR TITLE
Query script

### PR DESCRIPTION
**Pull request by baptistelebail**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Hi @baptistelebail @stevefaulkner. This looks really great, but what's the background this? I'll have a read on the notes in the wiki. 

I'm a bit worried that we keep using the webdevdata.org repo for projects that should be in separate repos. This repo should only contain the stuff pertaining to the webdevdata website.

**Comment by stevefaulkner** [comment]
@marcoscaceres my bad, how can we best associate this with webdevdata?

**Comment by mfaure** [comment]
Hi @marcoscaceres 

[ That's me that wanted to have such a script and @baptistelebail (former intern at our office) developed it. And I presented it to @stevefaulkner last week in Paris. ]

I thought that as long as this repository has got a getData.sh script, it would be suitable to have a "query" script also. 

Once compiled, this code gives you 3 scripts:
- webdevdata-query.sh
- webdevdata-stats-HTML-attributes.sh
- webdevdata-stats-HTML-tags.sh

The first one gives you the URLs (I mean files of WebDevData) matching a CSS-like query you pass as an argument. For instance all URLs having `select` tags with an `onchange` attribute. (We use such queries to fulfill [KBAccess](http://www.kbaccess.org/), a collaborative database of accessibility examples)

The second and third ones gives you, for each attributes and for each tags, their occurence in WebDevData.

Where do you think we should place this code ?

**Comment by marcoscaceres** [comment]
@mfaure I think we should move it into it's own repo - but I will need you to come up with a nice name for it :) . I will move the downloader code to a different place also.

**Comment by marcoscaceres** [comment]
@mfaure I've moved everything to a "query" repo: 
https://github.com/Webdevdata/query

**Comment by mfaure** [comment]
Great ! I will complete hte wiki page

**Comment by marcoscaceres** [comment]
Excellent, thanks @mfaure. Let me know if you want to rename the repo. Otherwise, you have full pull/push control over it. If you want us to review anything, just send a PR as normal.

**Pull request merged**
